export const designTokens = {
  color: {
    ink: {
      primary: "#123044",
      secondary: "#456274",
      muted: "#6f8796",
      inverse: "#ffffff",
      accent: "#2e7da3",
      accentStrong: "#1d5d80",
      danger: "#b33c57",
      warning: "#9a6b1f",
    },
    surface: {
      canvas: "#eef6f7",
      primary: "#fcfefd",
      secondary: "#f3f9fa",
      tertiary: "#e6f2f4",
      accent: "#e2f1f8",
      warning: "#fff7e8",
      danger: "#fff2f5",
      success: "#edf9f3",
    },
    border: {
      subtle: "#d8e6ea",
      strong: "#bdd0d7",
      accent: "#b8dbe9",
      warning: "#f2d9aa",
      danger: "#efc1cd",
      success: "#bedfca",
    },
    status: {
      infoBg: "#dff0f7",
      infoText: "#1d5d80",
      successBg: "#dff4e8",
      successText: "#0f6b54",
      warningBg: "#fff0ca",
      warningText: "#8c5a14",
      dangerBg: "#fde1e8",
      dangerText: "#9f1239",
    },
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 18,
    xl: 22,
    xxl: 28,
    pill: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  shadow: {
    card: {
      shadowColor: "#123044",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.06,
      shadowRadius: 18,
      elevation: 2,
    },
    raised: {
      shadowColor: "#123044",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.08,
      shadowRadius: 24,
      elevation: 3,
    },
    accent: {
      shadowColor: "#2e7da3",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.14,
      shadowRadius: 20,
      elevation: 4,
    },
  },
  typography: {
    title: {
      fontSize: 22,
      lineHeight: 28,
      fontWeight: "800" as const,
    },
    sectionTitle: {
      fontSize: 18,
      lineHeight: 24,
      fontWeight: "800" as const,
    },
    body: {
      fontSize: 14,
      lineHeight: 21,
      fontWeight: "400" as const,
    },
    label: {
      fontSize: 14,
      fontWeight: "700" as const,
    },
    eyebrow: {
      fontSize: 12,
      fontWeight: "700" as const,
      letterSpacing: 1.2,
      textTransform: "uppercase" as const,
    },
  },
} as const;

export type DesignTokens = typeof designTokens;
