export const authTestIds = {
  login: {
    screen: "auth-login-screen",
    emailInput: "auth-login-email-input",
    passwordInput: "auth-login-password-input",
    submitButton: "auth-login-submit-button",
    forgotPasswordLink: "auth-login-forgot-password-link",
    googleButton: "auth-login-google-button",
    registerLink: "auth-login-register-link",
    emailError: "auth-login-email-error",
    passwordError: "auth-login-password-error",
  },
  register: {
    screen: "auth-register-screen",
    nameInput: "auth-register-name-input",
    lastNameInput: "auth-register-lastname-input",
    identificationInput: "auth-register-identification-input",
    phoneInput: "auth-register-phone-input",
    emailInput: "auth-register-email-input",
    passwordInput: "auth-register-password-input",
    confirmPasswordInput: "auth-register-confirm-password-input",
    profileTypeClientRadio: "auth-register-profile-type-client-radio",
    profileTypeNurseRadio: "auth-register-profile-type-nurse-radio",
    hireDateInput: "auth-register-hire-date-input",
    submitButton: "auth-register-submit-button",
    loginLink: "auth-register-login-link",
    googleButton: "auth-register-google-button",
    nameError: "auth-register-name-error",
    lastNameError: "auth-register-lastname-error",
    identificationError: "auth-register-identification-error",
    phoneError: "auth-register-phone-error",
    emailError: "auth-register-email-error",
    passwordError: "auth-register-password-error",
    confirmPasswordError: "auth-register-confirm-password-error",
  },
  forgotPassword: {
    screen: "auth-forgot-password-screen",
    emailInput: "auth-forgot-password-email-input",
    submitButton: "auth-forgot-password-submit-button",
    enterCodeButton: "auth-forgot-password-enter-code-button",
    resendButton: "auth-forgot-password-resend-button",
    emailError: "auth-forgot-password-email-error",
    errorBanner: "auth-forgot-password-error-banner",
    successCard: "auth-forgot-password-success-card",
  },
  resetPassword: {
    screen: "auth-reset-password-screen",
    emailInput: "auth-reset-password-email-input",
    codeInput: "auth-reset-password-code-input",
    newPasswordInput: "auth-reset-password-new-password-input",
    confirmPasswordInput: "auth-reset-password-confirm-password-input",
    submitButton: "auth-reset-password-submit-button",
    emailError: "auth-reset-password-email-error",
    codeError: "auth-reset-password-code-error",
    passwordError: "auth-reset-password-password-error",
  },
} as const;

export function testProps(testId: string) {
  return {
    testID: testId,
    nativeID: testId,
  } as const;
}
