export const adminTestIds = {
  dashboard: {
    screen: "admin-dashboard-screen",
    actionsButton: "admin-dashboard-actions-button",
    requestsButton: "admin-dashboard-requests-button",
  },
  careRequests: {
    screen: "admin-care-list-screen",
    filterButton: "admin-care-list-filter-button",
    createButton: "admin-care-list-create-button",
    searchInput: "admin-care-list-search-input",
    detail: {
      screen: "admin-care-detail-screen",
      approveButton: "admin-care-detail-approve-button",
      rejectButton: "admin-care-detail-reject-button",
      assignButton: "admin-care-detail-assign-button",
      invoiceButton: "admin-care-detail-invoice-button",
      payButton: "admin-care-detail-pay-button",
      voidButton: "admin-care-detail-void-button",
      receiptButton: "admin-care-detail-receipt-button",
      updateButton: "admin-care-detail-update-button",
    },
    create: {
      screen: "admin-care-create-screen",
      clientSearchInput: "admin-care-create-client-search-input",
      descriptionInput: "admin-care-create-description-input",
      nurseInput: "admin-care-create-nurse-input",
      submitButton: "admin-care-create-submit-button",
    },
  },
  nurses: {
    listScreen: "admin-nurse-list-screen",
    detailScreen: "admin-nurse-detail-screen",
    create: {
      screen: "admin-nurse-create-screen",
      nameInput: "admin-nurse-create-name-input",
      lastNameInput: "admin-nurse-create-lastname-input",
      identificationInput: "admin-nurse-create-identification-input",
      phoneInput: "admin-nurse-create-phone-input",
      emailInput: "admin-nurse-create-email-input",
      passwordInput: "admin-nurse-create-password-input",
      confirmPasswordInput: "admin-nurse-create-confirm-password-input",
      specialtyInput: "admin-nurse-create-specialty-input",
      hireDateInput: "admin-nurse-create-hire-date-input",
      licenseInput: "admin-nurse-create-license-input",
      bankNameInput: "admin-nurse-create-bank-name-input",
      accountNumberInput: "admin-nurse-create-account-number-input",
      categoryInput: "admin-nurse-create-category-input",
      submitButton: "admin-nurse-create-submit-button",
    },
    edit: {
      screen: "admin-nurse-edit-screen",
      submitButton: "admin-nurse-edit-submit-button",
    },
  },
  clients: {
    listScreen: "admin-client-list-screen",
    detailScreen: "admin-client-detail-screen",
    create: {
      screen: "admin-client-create-screen",
      nameInput: "admin-client-create-name-input",
      lastNameInput: "admin-client-create-lastname-input",
      identificationInput: "admin-client-create-identification-input",
      phoneInput: "admin-client-create-phone-input",
      emailInput: "admin-client-create-email-input",
      passwordInput: "admin-client-create-password-input",
      confirmPasswordInput: "admin-client-create-confirm-password-input",
      submitButton: "admin-client-create-submit-button",
    },
  },
  payroll: {
    periodsScreen: "admin-payroll-periods-screen",
    nurseDetailScreen: "admin-payroll-nurse-detail-screen",
  },
  users: {
    listScreen: "admin-users-list-screen",
    detailScreen: "admin-users-detail-screen",
  },
  adminAccounts: {
    create: {
      screen: "admin-accounts-create-screen",
      emailInput: "admin-accounts-create-email-input",
      passwordInput: "admin-accounts-create-password-input",
      submitButton: "admin-accounts-create-submit-button",
    },
  },
} as const;
