export const adminTestIds = {
  dashboard: {
    screen: "admin-dashboard-screen",
    statusChip: "admin-dashboard-status-chip",
    errorBanner: "admin-dashboard-error-banner",
    primaryAction: "admin-dashboard-actions-button",
    actionsButton: "admin-dashboard-actions-button",
    requestsButton: "admin-dashboard-requests-button",
    notificationsButton: "admin-dashboard-notifications-button",
    alertButton: "admin-dashboard-alert-button",
    triageOverdueButton: "admin-dashboard-triage-overdue-button",
    triageUnassignedButton: "admin-dashboard-triage-unassigned-button",
    triageApprovalsButton: "admin-dashboard-triage-approvals-button",
    modulesToggleButton: "admin-dashboard-modules-toggle-button",
  },
  actionQueue: {
    screen: "admin-action-queue-screen",
    primaryAction: "admin-action-queue-open-button",
    severityChip: "admin-action-queue-severity-chip",
    statusChip: "admin-action-queue-severity-chip",
    errorBanner: "admin-action-queue-error-banner",
    summaryChip: "admin-action-queue-summary-chip",
  },
  notifications: {
    screen: "admin-notifications-screen",
    primaryAction: "admin-notifications-primary-action",
    severityChip: "admin-notifications-severity-chip",
    statusChip: "admin-notifications-severity-chip",
    errorBanner: "admin-notifications-error-banner",
    secondaryToggle: "admin-notifications-secondary-toggle",
    summaryChip: "admin-notifications-summary-chip",
  },
  careRequests: {
    screen: "admin-care-list-screen",
    filterButton: "admin-care-list-filter-button",
    createButton: "admin-care-list-create-button",
    searchInput: "admin-care-list-search-input",
    detail: {
      screen: "admin-care-request-detail-page",
      loadedMarker: "care-request-detail-loaded",
      statusBadge: "care-request-status-badge",
      errorBanner: "admin-care-request-error-banner",
      approveButton: "admin-care-detail-approve-button",
      rejectButton: "admin-care-detail-reject-button",
      assignButton: "admin-care-detail-assign-button",
      invoiceButton: "invoice-care-request-button",
      payButton: "pay-care-request-button",
      voidButton: "void-care-request-button",
      receiptButton: "generate-receipt-button",
      updateButton: "admin-care-detail-update-button",
    },
    billingRoutes: {
      backButton: "admin-care-billing-back-button",
      errorBanner: "admin-care-billing-error-banner",
      successBanner: "admin-care-billing-success-banner",
      invoiceScreen: "admin-care-request-invoice-screen",
      invoiceInput: "admin-care-request-invoice-input",
      invoiceSubmitButton: "admin-care-request-invoice-submit-button",
      payScreen: "admin-care-request-pay-screen",
      payInput: "admin-care-request-pay-input",
      paySubmitButton: "admin-care-request-pay-submit-button",
      voidScreen: "admin-care-request-void-screen",
      voidInput: "admin-care-request-void-input",
      voidSubmitButton: "admin-care-request-void-submit-button",
      receiptScreen: "admin-care-request-receipt-screen",
      receiptSubmitButton: "admin-care-request-receipt-submit-button",
    },
    create: {
      screen: "admin-care-create-screen",
      stepState: "admin-care-create-step-state",
      errorBanner: "admin-care-create-error-banner",
      clientSearchInput: "admin-care-create-client-search-input",
      dateInput: "admin-care-create-date-input",
      descriptionInput: "admin-care-create-description-input",
      nurseInput: "admin-care-create-nurse-input",
      customTypeInput: "admin-care-create-custom-type-input",
      priceOverrideInput: "admin-care-create-price-override-input",
      medicalSuppliesInput: "admin-care-create-medical-supplies-input",
      distanceFactorInput: "admin-care-create-distance-factor-input",
      complexityInput: "admin-care-create-complexity-input",
      submitButton: "admin-care-create-submit-button",
    },
  },
  nurses: {
    listScreen: "admin-nurse-list-screen",
    listCreateButton: "admin-nurse-list-create-button",
    listReadinessChip: "admin-nurse-readiness-chip",
    listErrorBanner: "admin-nurse-list-error-banner",
    detailScreen: "admin-nurse-detail-screen",
    detailStatusChip: "admin-nurse-detail-status-chip",
    detailErrorBanner: "admin-nurse-detail-error-banner",
    detailPrimaryAction: "admin-nurse-detail-primary-action",
    detailOperationalToggleButton: "admin-nurse-detail-operational-toggle-button",
    detailReviewButton: "admin-nurse-detail-review-button",
    create: {
      screen: "admin-nurse-create-screen",
      progressChip: "admin-nurse-create-progress-chip",
      errorBanner: "admin-nurse-create-error-banner",
      nameInput: "admin-nurse-create-name-input",
      lastNameInput: "admin-nurse-create-lastname-input",
      identificationInput: "admin-nurse-create-identification-input",
      phoneInput: "admin-nurse-create-phone-input",
      emailInput: "admin-nurse-create-email-input",
      passwordInput: "admin-nurse-create-password-input",
      confirmPasswordInput: "admin-nurse-create-confirm-password-input",
      specialtyInput: "admin-nurse-create-specialty-input",
      hireDateInput: "admin-nurse-create-hire-date-input",
      licenseInput: "admin-nurse-create-license-input",
      bankNameInput: "admin-nurse-create-bank-name-input",
      accountNumberInput: "admin-nurse-create-account-number-input",
      categoryInput: "admin-nurse-create-category-input",
      submitButton: "admin-nurse-create-submit-button",
    },
    review: {
      screen: "admin-nurse-review-screen",
      statusChip: "admin-nurse-review-status-chip",
      errorBanner: "admin-nurse-review-error-banner",
      specialtyInput: "admin-nurse-review-specialty-input",
      licenseInput: "admin-nurse-review-license-input",
      bankNameInput: "admin-nurse-review-bank-name-input",
      accountNumberInput: "admin-nurse-review-account-number-input",
      categoryInput: "admin-nurse-review-category-input",
      submitButton: "admin-nurse-review-submit-button",
    },
    edit: {
      screen: "admin-nurse-edit-screen",
      progressChip: "admin-nurse-edit-progress-chip",
      errorBanner: "admin-nurse-edit-error-banner",
      submitButton: "admin-nurse-edit-submit-button",
    },
  },
  clients: {
    listScreen: "admin-client-list-screen",
    primaryAction: "admin-client-list-primary-action",
    statusChip: "admin-client-list-status-chip",
    errorBanner: "admin-client-list-error-banner",
    detailScreen: "admin-client-detail-screen",
    detailPrimaryAction: "admin-client-detail-primary-action",
    detailStatusChip: "admin-client-detail-status-chip",
    detailErrorBanner: "admin-client-detail-error-banner",
    create: {
      screen: "admin-client-create-screen",
      progressChip: "admin-client-create-progress-chip",
      errorBanner: "admin-client-create-error-banner",
      nameInput: "admin-client-create-name-input",
      lastNameInput: "admin-client-create-lastname-input",
      identificationInput: "admin-client-create-identification-input",
      phoneInput: "admin-client-create-phone-input",
      emailInput: "admin-client-create-email-input",
      passwordInput: "admin-client-create-password-input",
      confirmPasswordInput: "admin-client-create-confirm-password-input",
      submitButton: "admin-client-create-submit-button",
    },
  },
  payroll: {
    periodsScreen: "admin-payroll-periods-screen",
    nurseDetailScreen: "admin-payroll-nurse-detail-screen",
    // UC-008: Nurse Payroll Detail
    periodDetailPage: "admin-payroll-period-detail-page",
    periodDetailLoaded: "payroll-period-detail-loaded",
    periodStatusBadge: "admin-payroll-period-status-badge",
    nurseSummaryTable: "payroll-nurse-summary-table",
    nurseRow: "payroll-nurse-row",
    nurseDetailPanel: "nurse-payroll-detail-panel",
    nurseDetailLoaded: "nurse-payroll-detail-loaded",
    nurseServicesTable: "nurse-payroll-services-table",
    nurseDeductionsTable: "nurse-payroll-deductions-table",
    // UC-009: Payroll Period Immutability
    overrideRequestButton: "override-request-button",
    errorToast: "error-toast",
    linesTable: "payroll-lines-table",
  },
  users: {
    listScreen: "admin-users-list-screen",
    primaryAction: "admin-users-primary-action",
    statusChip: "admin-users-status-chip",
    errorBanner: "admin-users-error-banner",
    detailScreen: "admin-users-detail-screen",
    detailPrimaryAction: "admin-users-detail-primary-action",
    detailStatusChip: "admin-users-detail-status-chip",
    detailErrorBanner: "admin-users-detail-error-banner",
  },
  adminAccounts: {
    create: {
      screen: "admin-accounts-create-screen",
      reviewChip: "admin-accounts-create-review-chip",
      errorBanner: "admin-accounts-create-error-banner",
      nameInput: "admin-accounts-create-name-input",
      lastNameInput: "admin-accounts-create-lastname-input",
      identificationInput: "admin-accounts-create-identification-input",
      phoneInput: "admin-accounts-create-phone-input",
      emailInput: "admin-accounts-create-email-input",
      passwordInput: "admin-accounts-create-password-input",
      confirmPasswordInput: "admin-accounts-create-confirm-password-input",
      submitButton: "admin-accounts-create-submit-button",
    },
  },
  settings: {
    screen: "admin-settings-screen",
    list: "admin-settings-list",
    refreshButton: "admin-settings-refresh-btn",
    errorBanner: "admin-settings-error",
    settingCard: "admin-setting-card",
    editPanel: "admin-setting-edit-panel",
    valueInput: "admin-setting-value-input",
    saveButton: "admin-setting-save-btn",
    cancelButton: "admin-setting-cancel-btn",
  },
  shifts: {
    screen: "admin-shifts-screen",
    list: "admin-shifts-list",
    errorBanner: "admin-shifts-error",
    filterToggleButton: "admin-shifts-filter-toggle",
    refreshButton: "admin-shifts-refresh-btn",
    statusChip: "admin-shifts-status-chip",
    shiftCard: "admin-shift-card",
    detailPanel: "admin-shift-detail-panel",
    prevButton: "admin-shifts-prev-btn",
    nextButton: "admin-shifts-next-btn",
    startDateInput: "admin-shifts-start-date-input",
    endDateInput: "admin-shifts-end-date-input",
    searchButton: "admin-shifts-search-btn",
  },
  auditLogs: {
    screen: "admin-audit-logs-screen",
    list: "admin-audit-logs-list",
    errorBanner: "admin-audit-logs-error",
    filterToggleButton: "admin-audit-logs-filter-toggle",
    refreshButton: "admin-audit-logs-refresh-btn",
    actionFilterInput: "admin-audit-logs-action-input",
    entityTypeFilterInput: "admin-audit-logs-entity-type-input",
    searchButton: "admin-audit-logs-search-btn",
    clearButton: "admin-audit-logs-clear-btn",
    logCard: "admin-audit-log-card",
    detailPanel: "admin-audit-log-detail-panel",
    prevButton: "admin-audit-logs-prev-btn",
    nextButton: "admin-audit-logs-next-btn",
  },
  catalog: {
    screen: "admin-catalog-screen",
    tabBar: "admin-catalog-tab-bar",
    tab: "admin-catalog-tab",
    cardsList: "admin-catalog-cards-list",
    catalogCard: "admin-catalog-card",
    pricingPreviewButton: "admin-catalog-pricing-preview",
    editPanel: "admin-catalog-edit-panel",
    pricingPreviewPanel: "admin-catalog-pricing-preview-panel",
    toggleInactiveButton: "admin-catalog-toggle-inactive",
    refreshButton: "admin-catalog-refresh-btn",
    createButton: "admin-catalog-create-btn",
    errorBanner: "admin-catalog-error",
    saveButton: "admin-catalog-save-btn",
    cancelButton: "admin-catalog-cancel-btn",
  },
} as const;
