export const adminTestIds = {
  dashboard: {
    screen: "admin-dashboard-screen",
    statusChip: "admin-dashboard-status-chip",
    errorBanner: "admin-dashboard-error-banner",
    primaryAction: "admin-dashboard-actions-button",
    actionsButton: "admin-dashboard-actions-button",
    requestsButton: "admin-dashboard-requests-button",
    notificationsButton: "admin-dashboard-notifications-button",
    alertButton: "admin-dashboard-alert-button",
    triageOverdueButton: "admin-dashboard-triage-overdue-button",
    triageUnassignedButton: "admin-dashboard-triage-unassigned-button",
    triageApprovalsButton: "admin-dashboard-triage-approvals-button",
    modulesToggleButton: "admin-dashboard-modules-toggle-button",
  },
  actionQueue: {
    screen: "admin-action-queue-screen",
    primaryAction: "admin-action-queue-open-button",
    severityChip: "admin-action-queue-severity-chip",
    statusChip: "admin-action-queue-severity-chip",
    errorBanner: "admin-action-queue-error-banner",
    summaryChip: "admin-action-queue-summary-chip",
  },
  notifications: {
    screen: "admin-notifications-screen",
    primaryAction: "admin-notifications-primary-action",
    severityChip: "admin-notifications-severity-chip",
    statusChip: "admin-notifications-severity-chip",
    errorBanner: "admin-notifications-error-banner",
    secondaryToggle: "admin-notifications-secondary-toggle",
    summaryChip: "admin-notifications-summary-chip",
  },
  careRequests: {
    screen: "admin-care-list-screen",
    filterButton: "admin-care-list-filter-button",
    createButton: "admin-care-list-create-button",
    searchInput: "admin-care-list-search-input",
    detail: {
      screen: "admin-care-request-detail-page",
      loadedMarker: "care-request-detail-loaded",
      statusBadge: "care-request-status-badge",
      errorBanner: "admin-care-request-error-banner",
      approveButton: "admin-care-detail-approve-button",
      rejectButton: "admin-care-detail-reject-button",
      assignButton: "admin-care-detail-assign-button",
      invoiceButton: "invoice-care-request-button",
      payButton: "pay-care-request-button",
      voidButton: "void-care-request-button",
      receiptButton: "generate-receipt-button",
      updateButton: "admin-care-detail-update-button",
    },
    billingRoutes: {
      backButton: "admin-care-billing-back-button",
      errorBanner: "admin-care-billing-error-banner",
      successBanner: "admin-care-billing-success-banner",
      invoiceScreen: "admin-care-request-invoice-screen",
      invoiceInput: "admin-care-request-invoice-input",
      invoiceSubmitButton: "admin-care-request-invoice-submit-button",
      payScreen: "admin-care-request-pay-screen",
      payInput: "admin-care-request-pay-input",
      paySubmitButton: "admin-care-request-pay-submit-button",
      voidScreen: "admin-care-request-void-screen",
      voidInput: "admin-care-request-void-input",
      voidSubmitButton: "admin-care-request-void-submit-button",
      receiptScreen: "admin-care-request-receipt-screen",
      receiptSubmitButton: "admin-care-request-receipt-submit-button",
    },
    create: {
      screen: "admin-care-create-screen",
      clientSearchInput: "admin-care-create-client-search-input",
      descriptionInput: "admin-care-create-description-input",
      nurseInput: "admin-care-create-nurse-input",
      submitButton: "admin-care-create-submit-button",
    },
  },
  nurses: {
    listScreen: "admin-nurse-list-screen",
    detailScreen: "admin-nurse-detail-screen",
    create: {
      screen: "admin-nurse-create-screen",
      nameInput: "admin-nurse-create-name-input",
      lastNameInput: "admin-nurse-create-lastname-input",
      identificationInput: "admin-nurse-create-identification-input",
      phoneInput: "admin-nurse-create-phone-input",
      emailInput: "admin-nurse-create-email-input",
      passwordInput: "admin-nurse-create-password-input",
      confirmPasswordInput: "admin-nurse-create-confirm-password-input",
      specialtyInput: "admin-nurse-create-specialty-input",
      hireDateInput: "admin-nurse-create-hire-date-input",
      licenseInput: "admin-nurse-create-license-input",
      bankNameInput: "admin-nurse-create-bank-name-input",
      accountNumberInput: "admin-nurse-create-account-number-input",
      categoryInput: "admin-nurse-create-category-input",
      submitButton: "admin-nurse-create-submit-button",
    },
    edit: {
      screen: "admin-nurse-edit-screen",
      submitButton: "admin-nurse-edit-submit-button",
    },
  },
  clients: {
    listScreen: "admin-client-list-screen",
    detailScreen: "admin-client-detail-screen",
    create: {
      screen: "admin-client-create-screen",
      nameInput: "admin-client-create-name-input",
      lastNameInput: "admin-client-create-lastname-input",
      identificationInput: "admin-client-create-identification-input",
      phoneInput: "admin-client-create-phone-input",
      emailInput: "admin-client-create-email-input",
      passwordInput: "admin-client-create-password-input",
      confirmPasswordInput: "admin-client-create-confirm-password-input",
      submitButton: "admin-client-create-submit-button",
    },
  },
  payroll: {
    periodsScreen: "admin-payroll-periods-screen",
    nurseDetailScreen: "admin-payroll-nurse-detail-screen",
    // UC-008: Nurse Payroll Detail
    periodDetailPage: "admin-payroll-period-detail-page",
    periodDetailLoaded: "payroll-period-detail-loaded",
    periodStatusBadge: "payroll-period-status-badge",
    nurseSummaryTable: "payroll-nurse-summary-table",
    nurseRow: "payroll-nurse-row",
    nurseDetailPanel: "nurse-payroll-detail-panel",
    nurseDetailLoaded: "nurse-payroll-detail-loaded",
    nurseServicesTable: "nurse-payroll-services-table",
    nurseDeductionsTable: "nurse-payroll-deductions-table",
    // UC-009: Payroll Period Immutability
    overrideRequestButton: "override-request-button",
    errorToast: "error-toast",
    linesTable: "payroll-lines-table",
  },
  users: {
    listScreen: "admin-users-list-screen",
    detailScreen: "admin-users-detail-screen",
  },
  adminAccounts: {
    create: {
      screen: "admin-accounts-create-screen",
      emailInput: "admin-accounts-create-email-input",
      passwordInput: "admin-accounts-create-password-input",
      submitButton: "admin-accounts-create-submit-button",
    },
  },
} as const;
