export const careRequestTestIds = {
  list: {
    screen: "care-request-list-screen",
  },
  detail: {
    screen: "care-detail-page",
    infoSection: "care-detail-info-section",
    statusChip: "care-detail-status-chip",
    errorBanner: "care-detail-error-banner",
    primaryAction: "price-breakdown-verify-button",
    pricingReviewPanel: "price-verification-modal",
    pricingReviewConfirmButton: "price-verification-confirm-button",
    pricingBreakdownToggle: "care-detail-pricing-breakdown-toggle",
    pricingSheet: "care-detail-pricing-sheet",
    assignmentSheetTrigger: "care-detail-assignment-sheet-trigger",
    assignmentSheet: "care-detail-assignment-sheet",
    assignmentSearchInput: "care-detail-assignment-search-input",
    assignmentNurseOption: (userId: string) => `care-detail-assignment-nurse-${userId}`,
    assignmentConfirmButton: "care-detail-assignment-confirm-button",
    overflowTrigger: "care-detail-overflow-trigger",
    overflowSheet: "care-detail-overflow-sheet",
    overflowAction: (key: string) => `care-detail-overflow-action-${key}`,
    // Billing / payment status section (client-facing)
    paymentStatusCard: "care-detail-payment-status-card",
    paymentStatusBadge: "care-detail-payment-status-badge",
    paymentStatusTotal: "care-detail-payment-status-total",
    paymentStatusInvoiceNumber: "care-detail-payment-status-invoice-number",
    paymentStatusInvoicedAt: "care-detail-payment-status-invoiced-at",
    paymentStatusPaidAt: "care-detail-payment-status-paid-at",
    receiptDownloadButton: "care-detail-receipt-download-button",
    // Nurse-facing own-pay row (replaces the client price for NURSE viewers).
    nursePayCard: "care-detail-nurse-pay-card",
    nursePayValue: "care-detail-nurse-pay-value",
    // Nurse assignment accept/reject (status `Asignada`).
    acceptAssignmentButton: "care-detail-accept-assignment-button",
    rejectAssignmentButton: "care-detail-reject-assignment-button",
    rejectAssignmentSheet: "care-detail-reject-assignment-sheet",
    rejectAssignmentReasonInput: "care-detail-reject-assignment-reason-input",
    rejectAssignmentConfirmButton: "care-detail-reject-assignment-confirm-button",
  },
  create: {
    screen: "care-request-create-screen",
    intentStep: "create-care-request-intent-step",
    detailsStep: "create-care-request-details-step",
    reviewStep: "create-care-request-review-step",
    intentOption: (intent: string) => `create-care-request-intent-${intent}`,
    nextButton: "create-care-request-next-button",
    backStepButton: "create-care-request-back-step-button",
    descriptionInput: "create-care-request-description-input",
    suggestedNurseInput: "create-care-request-suggested-nurse-input",
    suggestedNurseOptions: "create-care-request-suggested-nurse-options",
    clientInput: "create-care-request-client-input",
    clientOptions: "create-care-request-client-options",
    clientOption: (userId: string) => `create-care-request-client-option-${userId}`,
    clientClearButton: "create-care-request-client-clear-button",
    submitButton: "create-care-request-submit-button",
  },
} as const;
